### ISSUE TITLE
[patch] ArgumentNullException

### ISSUE THREAD

**Issue by justinmk** [mausch/SolrNet#165]
Thanks for SolrNet!

I'm running into an occasional (1 in ~100k posts) ArgumentNullException in SolrDocumentSerializer. `XElement.Value` does not allow null values, but `RemoveControlCharacters()` may return null. In that case, I'm assuming that there is no reason to add the node at all.

```patch
diff --git a/SolrNet/Impl/SolrDocumentSerializer.cs b/SolrNet/Impl/SolrDocumentSerializer.cs
index 15ccf3d..252fa37 100644
--- a/SolrNet/Impl/SolrDocumentSerializer.cs
+++ b/SolrNet/Impl/SolrDocumentSerializer.cs
@@ -69,8 +69,11 @@ namespace SolrNet.Impl {
                         fieldNode.Add(boostAtt);
                     }
 
-                    fieldNode.Value = RemoveControlCharacters(n.FieldValue);
-                    docNode.Add(fieldNode);
+                    var v = RemoveControlCharacters(n.FieldValue);
+                    if (v != null) {
+                        fieldNode.Value = v;
+                        docNode.Add(fieldNode);
+                    }
                 }
             }
             return docNode;
```

**Comment by wormangel** [comment]
Was this ever merged? I'm facing the same problem here

**Comment by justinmk** [comment]
No, I'm using this patch in production though.

**Comment by justinmk** [comment]
Also, given the logic at https://github.com/mausch/SolrNet/blob/6c0022c91b3902dbcebb36d38e280d4f30bed90f/SolrNet/Impl/SolrDocumentSerializer.cs#L59 there's really no good reason not to merge this.

**Comment by mausch** [comment]
Merged, thanks!
