### ISSUE TITLE
solr.Query fails

### ISSUE THREAD

**Issue by jborden13** [mausch/SolrNet#169]
The code below used to work, but now it only returns "The remote server returned an error: (500) Internal Server Error":

```
Startup.Init<SolrResult>("http://xxx.xxx.xxx.x:xxxx/solr");
var solr = ServiceLocator.Current.GetInstance<ISolrOperations<SolrResult>>();
var query = (new SolrQuery("title:test"));
var results = solr.Query(query);
```

When I request directly from Solr in the browser it works normally:

http://xxx.xxx.xxx.x:xxxx/solr/query?q=title:test

The error is very generic and I can't track down what the actual cause is, any help is appreciated.

**Comment by mausch** [comment]
You're probably using an old build of SolrNet. Update to a recent build and it will probably work or at least it will give you more information about the error.
