### ISSUE TITLE
Site for SolrNet

### ISSUE THREAD

**Issue by sergey-tihon** [mausch/SolrNet#178]
@mausch Would you like to have auto-generated `SolrNet` site with documentation (integrated into build script)? Similar to the one that [ProjectScaffold](http://fsprojects.github.io/ProjectScaffold/) provides.

**Comment by mausch** [comment]
I think `doxygen` (the tool currently used to generate offline reference docs for SolrNet) can generate HTML too, so it should be possible to do this with a few changes to the existing FAKE build script.
The problem, however, is that I want to have immediately-browsable documentation per commit (or at least per branch) i.e. I want fully-versioned documentation. The current documentation system in SolrNet does this, which doesn't seem to be possible when using `gh-pages` as far as I can tell. In other words, `gh-pages` only show me *one* version of the documentation, presumably from `master`, but that means that users never really know about what version of the library is the documentation talking about.

It would also be lovely to get compiler-checked documentation but that only seems to work with `FSharp.Formatting` at the moment, which of course only handles F# code AFAIK.
Without compiler checks, generated documentation is of very little value IMHO. I just use the Visual Studio's object/metadata browser.

**Comment by sergey-tihon** [comment]
Ok

**Comment by mausch** [comment]
On second thought, it should be possible to generate per-branch docs if the generator script pushes its output to e.g. /master/index.html .
Though I still don't see much benefit over https://github.com/mausch/SolrNet/blob/master/Documentation/README.md . Somewhat prettier navigation maybe? Doesn't seem to be worth it IMHO...
