### ISSUE TITLE
NuGet -pre release doesn't work with Solr 4

### ISSUE THREAD

**Issue by Laoujin** [mausch/SolrNet#184]
StackOverflow quote:
"Please note, in addition to Paige Cook's answer, that **currently (Jan 2015) NuGet doesn't hold the latest version.** Using Install-Package SolrNet -Pre you get an assembly with version number 0.4.0.2002, which is the current number, but there is a more recent version within this version number (tricky!). To fix the problem, use GitHub or SolrNightlyBuilds instead."

http://stackoverflow.com/questions/21719027/solr-commit-returns-400-bad-request-in-log-unknown-commit-parameter-waitfl

I did a build from the latest GitHub source and it works now...

**Comment by mausch** [comment]
Please see https://github.com/mausch/SolrNet/blob/master/Documentation/README.md#downloads , that'll always be the authoritative source.
