### ISSUE TITLE
How to use different solr requesthandlers for different webpages

### ISSUE THREAD

**Issue by Ankita-XIT** [mausch/SolrNet#188]
I am using solrnet. I have two handler. 1) /Default handler 2) /mysearch handler
1st one is used for few of webpages & 2nd one is used for other webpages.
So, how can I use both of handlers for different webpages?
Please advise me this is possible or not?

**Comment by mausch** [comment]
https://groups.google.com/d/msg/solrnet/ZA-bv9dkh_0/NZSSF0p-U1gJ
