### ISSUE TITLE
Need more info about issue 189 raised [abt pdf indexing in solr] 

### ISSUE THREAD

**Issue by ravi032** [mausch/SolrNet#191]
We had a discussion on google group link https://groups.google.com/d/msg/solrnet/2_5XF3zVRW8/lFsRSQ1jzOgJ about pdf index feature in solr and how solr net works. You provided one example link. But I require more detailed information about what different options I can use with solr net at time of pdf/doc indexing. I have asked my detailed questions in this link. Kindly help.

**Comment by mausch** [comment]
Please keep the conversation where it was started. As I mentioned on that thread, if you see a 400 error you need to get the logs.
