### ISSUE TITLE
Is SolrCoreAdmin class missing on SolrNet 0.4.0.4001 version?

### ISSUE THREAD

**Issue by dbarriop** [mausch/SolrNet#197]
Hello,

One partner passed me a project with SolrNet 0.4.0.2002 version. That code used the SolrCoreAdmin class an other classes as CoreResult, etc.

Are they included in the current SolrNet 0.4.0.4001 version? I cannot find it.

Is needed another nuget package?

Thanks

**Comment by mausch** [comment]
Please see https://groups.google.com/d/msg/solrnet/2XnuMpqStfc/56sK2uZP-lIJ

**Comment by dbarriop** [comment]
thanks!!!
