### ISSUE TITLE
SolrNet and Dynamic fields

### ISSUE THREAD

**Issue by a3code** [mausch/SolrNet#209]
How SolrNet is working with Dynamic Data ?
What would be a best practice ?
Should I my class manually ?
Can I describe some attribute with dynamic post-fix ?  
```c#

public class Product {
    [SolrField("price_t")]
    public decimal Price { get; set; }

```

**Comment by mausch** [comment]
Check out https://github.com/mausch/SolrNet/blob/master/Documentation/Mapping.md#dictionary-mappings-and-dynamic-fields
