### ISSUE TITLE
Constructing StartOrCursor.Cursor

### ISSUE THREAD

**Issue by mhov** [mausch/SolrNet#213]
Is there a practical reason the StartOrCursor.Cursor has an ```internal``` constructor?  I have a case where I'm exposing solr results through a rest api.  I'd like to be able to return the next cursor and let the user send it back to me for the next page to do something like: 
``` C#
queryOptions.StartOrCursor = new StartOrCursor.Cursor([cursor string from request]);
```
but currently the only way to ```queryOptions.StartOrCursor``` is from a previous ```queryResult.NextCursorMark``` which can't be done through stateless requests.

**Comment by mausch** [comment]
It was to prevent invalid values (the constructor was only used when parsing the response).
But yeah, you're right, I just made it public.

Cheers
