### ISSUE TITLE
Output xml in not well formed

### ISSUE THREAD

**Issue by poonaminfor** [mausch/SolrNet#214]
HI,
         i am trying make solr request ,i am getting result with style tags and all(HTML format).I don want result in this format.I want is simple XML or json like below:
{"responseHeader":{"status":0,"QTime":0,"params":{"q":"_:_","wt":"json"}},"response":{"numFound":1,"start":0,"maxScore":1.0,"docs":[{"solid":"45","_version_":1513537590450454528,"score":1.0}]},"facet_counts":{"facet_queries":{},"facet_fields":{},"facet_dates":{},"facet_ranges":{},"facet_intervals":{},"facet_heatmaps":{}}}

**Comment by mausch** [comment]
Hi,

If you mean you want the raw XML response instead of .NET SolrNet objects, have a look at this blogpost: http://bugsquash.blogspot.co.uk/2010/03/low-level-solrnet.html

Cheers

**Comment by mausch** [comment]
@poonaminfor did the previous comment solve your issue?
