### ISSUE TITLE
How to Equal Query by SolrNet?

### ISSUE THREAD

**Issue by qiankunpig** [mausch/SolrNet#219]
Excuse me， My Solr inside a field called Title use the text_ik word segmentation is now the default is fuzzy query I now want to use similar and Equal query way how to achieve?

**Comment by mausch** [comment]
Sorry, I can't understand the question.

**Comment by mhov** [comment]
I think i get the question, if you want EXACT matches (including capitalization) you should try the field type "string" instead of "text_ik".  

ex. schema.xml
```<field name="[fieldname]" type="string" indexed="true" />```

**Comment by mausch** [comment]
@qiankunpig did the previous comment solve your problem?

**Comment by louzhenyu** [comment]
you can try q=Title:"a title", double quotation marks will let solr search exact Title which equals "a title"
