### ISSUE TITLE
PivotFields no longer working

### ISSUE THREAD

**Issue by whittssg** [mausch/SolrNet#224]
I just updated to the latest version via nuget and now 'PivotFields' could not be found:

Sample code:

```csharp
solroptions.Facet = new FacetParameters
                {
                    Queries = new[]
                    {
                        new SolrFacetPivotQuery
                        {
                            Fields = new[] {new PivotFields("a", "b", "c", "d")},
                            
                            MinCount = 1,
                            
                        }
                    },
                    
                };
```

Thanks,

**Comment by mausch** [comment]
Weird, I haven't changed the [serializer](https://github.com/mausch/SolrNet/blob/master/SolrNet/Impl/FacetQuerySerializers/SolrFacetPivotQuerySerializer.cs) or the [response parser](https://github.com/mausch/SolrNet/blob/master/SolrNet/Impl/ResponseParsers/FacetsResponseParser.cs) since 2013... what version of SolrNet were you running before? And what's your Solr version?

**Comment by mausch** [comment]
Also can you compare your Solr XML output with the response we're testing against? https://github.com/mausch/SolrNet/blob/8a393343dec31e5116e02f19f480b5f820bcaa12/SolrNet.Tests/Resources/responseWithFacetPivoting.xml

**Comment by whittssg** [comment]
I was previously on build 0.4.0.2002. After upgrading via Nuget i am now on 0.4.0.4001. I cannot get the response since i can longer build: The type or namespace name 'PivotFields' could not be found (are you missing a using directive or an assembly reference?

Everything else seems to be recognized by visual studio. Thanks

**Comment by mausch** [comment]
Ah, I thought it was failing at runtime.

You were probably using a nightly build and the version number is not entirely accurate. 
Please use https://www.nuget.org/packages/SolrNet/0.5.0-alpha2 instead.

**Comment by whittssg** [comment]
Yeh it works fine on the latest alpha.. Is that stable enough to run in prod? Thanks

**Comment by mausch** [comment]
Yes it is.

**Comment by whittssg** [comment]
cool thanks
