### ISSUE TITLE
SolrNet, MVC, Sitecore

### ISSUE THREAD

**Issue by ksivanandan** [mausch/SolrNet#227]
Hello

I am new to Sitecore,SoleNet. I have installed and configured Solr to work with Sitecore and I am able to see results. 
I am now using code.

I added the connection string to UnityMVCActivator.cs in the Start()
`Startup.Init<SearchResultsViewModel>("http://localhost:8983/solr/sitecore_web_index");`

In my controller - Actionresults Index()
`var solr = ServiceLocator.Current.GetInstance<ISolrOperations<SearchResultsViewModel>>();`

I get this error
```
[InvalidOperationException: The type ISolrOperations`1 does not have an accessible constructor.]
   Microsoft.Practices.ObjectBuilder2.DynamicMethodConstructorStrategy.ThrowForNullExistingObject(IBuilderContext context) +226
   lambda_method(Closure , IBuilderContext ) +39
   Microsoft.Practices.ObjectBuilder2.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context) +33
   Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context) +337
   Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context) +396
   Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides) +238

[ResolutionFailedException: Resolution of the dependency failed, type = "SolrNet.ISolrOperations`1[Niddk.Model.SearchResultsViewModel]", name = "(none)".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The type ISolrOperations`1 does not have an accessible constructor.
```
-----------------------------------------------
At the time of the exception, the container was:

```
  Resolving SolrNet.ISolrOperations`1[Niddk.Model.SearchResultsViewModel],(none)
]
   Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides) +500
   Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides) +20
   Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key) +55

[ActivationException: Activation error occured while trying to get instance of type ISolrOperations`1, key ""]
   Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key) +156
   Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance() +62
   Niddk.Web.Controllers.SearchController.Index() in C:\Users\ksivanandan\Source\Repos\web\Niddk\Niddk.Web\Controllers\SearchController.cs:23
   lambda_method(Closure , ControllerBase , Object[] ) +87
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +229
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35
   System.Web.Mvc.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12() +80
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +453
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +453
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +533
```

My ViewModel

```csharp
public class SearchResultsViewModel
    {
        
        [SolrField("headline_t")]
        public string Headline { get; set; }
        

    }
```
Any help is greatly appreciated.

Thank you!

**Comment by xaviermorera** [comment]
I may be reading your code wrong or something might be missing from the post but you are not passing the type:

In my controller - Actionresults Index() 

`var solr = ServiceLocator.Current.GetInstance<[you are missing this part]>();`

When using generics you need to specify the type. I thinks this part would not even compile because of the .GetInstance>() being incomplete.

**Comment by mausch** [comment]
As Xavier noted, you have to be careful when posting code on github issues, it will swallow `<` characters by default unless you mark the snippet as preformatted text.

**Comment by mausch** [comment]
I think the problem here is that you're registering SolrNet in the built-in IoC container but then you're resolving it from Unity.

Either register `ISolrOperations<SearchResultsViewModel>` in Unity resolving it from the built-in container or use the Unity integration.

**Comment by ksivanandan** [comment]
Thank you both so much for your quick response. I will try and see how I can get this working and will let you know. The Sample Application is really very helpful.

**Comment by ksivanandan** [comment]
Hello

I need some help please to set this up.

I have my unityConfig.cs which has code

Container
private static Lazy<IUnityContainer> container = new Lazy<IUnityContainer>(() =>
        {
            var container = new UnityContainer();
            RegisterTypes(container);
            return container;
        });


RegisterType
container.RegisterType<INewsReader, NewsReader>();


Not sure how to add this:

var solrServers = new SolrServers {
        new SolrServerElement {
          Id = "test",
          Url = "htp://localhost:8893",
          DocumentType = typeof (Entity).AssemblyQualifiedName,
        }
};
container = new UnityContainer();
new SolrNetContainerConfiguration().ConfigureContainer(solrServers, container);


and what dlls are needed..

Also my controller code:

readonly ISolrOperations<SearchResultsViewModel> _searchResults;
public SearchController(ISolrOperations<SearchResultsViewModel> searchResults)
        {
            _searchResults = searchResults;
        }


Thanks much!
Kalpana

**Comment by ksivanandan** [comment]
Hello

I got this to work!

var solrServers = new SolrServers {
                new SolrServerElement {
                    Id = "solr",
                    Url = "http://localhost:8983/solr/sitecore_web_index",
                    DocumentType = typeof (SearchResultsViewModel).AssemblyQualifiedName,

                }
            };

            (new SolrNetContainerConfiguration()).ConfigureContainer(solrServers, container);


 container.Resolve<ISolrOperations<SearchResultsViewModel>>();

Thank You!
