### ISSUE TITLE
No strong name for 0.5.0-alpha2 

### ISSUE THREAD

**Issue by thehudi** [mausch/SolrNet#230]
The [NuGet Package](https://www.nuget.org/packages/SolrNet/0.5.0-alpha2) does not have a strong name and cannot be used in applications which want to used signed assemblies.

**Comment by mausch** [comment]
If I add a strong name, then people ask for a non-strongly-named package.
If I remove it, people ask for a strongly-named package.
There is no winning with this.

Microsoft have long recognised that strong naming was generally a bad idea, so it should not be a default.
If you need strong names, try something like https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/ or https://www.nuget.org/packages/Nivot.StrongNaming/ or https://www.nuget.org/packages/StrongNamer/
