### ISSUE TITLE
Issue With fq=

### ISSUE THREAD

**Issue by storment** [mausch/SolrNet#236]
Hi,
I was running SolrNet 0.4.0.2002 but had to restore my nuget packages.  This is no longer available so I was upgraded to 0.4.0.4001. My issue is that the fq part of my generated command has changed from fq=parameter: (1 OR 2) 
to
fq=(parameter: 1 OR 2)
This breaks the search and means only items 1 are returned.  Is there a way to get 0.4.0.2002 back on Nuget?
Thanks

**Comment by mausch** [comment]
Can you post the code you're using to generate this filter query?

**Comment by storment** [comment]
Sure,
  The code is below and mediatypefq = "1 OR 2 OR 5".
```
  var q = solr.Query(new SolrQueryByField("autocomplete", searchTerm) { Quoted = false }, new QueryOptions
        {                    
            FilterQueries = new ISolrQuery[] 
            {
                new SolrQueryByField("itemtype", mediatypefq) { Quoted = false }
            },
            Rows = resultsPerPage,
            Start = startResult,
            Grouping = new GroupingParameters()
            {
                Fields = new[] { "parent_id" },
                Main = true
            },
            OrderBy = sortOrder,
            Fields = new[] { "parent_id", "itemtype", "score", "heat" }
        });
```

I updated to 0.5.0-alpha2 and it started working as expected again. I just had to change
```Start = startResult```
to 
```StartOrCursor = new StartOrCursor.Start(startResult)```
to remove the deprecated warnings although it still worked without that change.

**Comment by mausch** [comment]
Cool, so it's working fine on 0.5.0-alpha2 then?

**Comment by storment** [comment]
Yes perfectly thanks. Hopefully if anyone else has this issue they will see this thread and make the upgrade as well.
