### ISSUE TITLE
SolrNet Highlight

### ISSUE THREAD

**Issue by ksivanandan** [mausch/SolrNet#243]
Hello

I have implemented the SolrNet sample App and I am looking to do the Highlights. I configured solr and I see <lst name="highlights"> now I want to integrate it with my app and show it on the results page. I am display Title, Url. I would like to display snippet (where the keyword appears) and highlight the words on the title, url and Snippet. Are there any examples?

Controller
var queryOption = new QueryOptions
                {
                    FilterQueries = BuildFilterQueries(parameters),
                    Rows = parameters.PageSize,
                    Start = start,
                    SpellCheck = new SpellCheckingParameters
                    {
                        Collate = true
                    },
                    Highlight = new HighlightingParameters
                    {
                        Fragsize = 250,
                        Fields = new[] { "*" },
                        BeforeTerm = "<b>",
                        AfterTerm = "</b>",
                        Snippets = 1
                    }

                };

Index
@foreach (var item in Model.EntireSiteResults)
        {
            <li>
                <h2><a href="@item.PageUrl">@item.Title</a></h2>
                <span class="sr-url"><a href="@item.PageUrl">@item.PageUrl</a></span>
                <p>@item.Description</p>
            </li>
        }

Any help is greatly appreciated

Thanks
Kalpana

**Comment by xaviermorera** [comment]
Example is in the documentation: https://github.com/mausch/SolrNet/blob/master/Documentation/Highlighting.md

Additionally you can see this thread in SO for configuration: http://stackoverflow.com/questions/20097314/highlighting-in-solrnet

**Comment by ksivanandan** [comment]
Thank you for your quick response.

I did see both the thread but not sure where I should set this up? At the Controller after I get the result set? Should I work on the results? Also, I would have to show the highlight on Title, Url, Description and Snippet.
var results = _searchResults.Query(BuildQuery(parameters), queryOption);
                        view = new SearchView
                        {
                            EntireSiteResults = results,
                            Search = parameters,
                            TotalCount = results.NumFound,
                            DidYouMean = GetSpellCheckingResult(results)
                        };

Or at Index
@foreach (var item in Model.EntireSiteResults)
        {
            <a href="@item.PageUrl">@item.Title</a>
            <a href="@item.PageUrl">@item.PageUrl</a>
            @item.Description
        }

Thanks

**Comment by xaviermorera** [comment]
You have first to specify that you want to use highlighting and over which fields. The * is "good" but not great if you have many fields that you don't want to highlight - also depends on your qf. But in any case, you need to:
- Set your highlighting parameters in QueryOptions and pass to .Query()
- And then when you get your results, you will get Title, PageUrl and Description without highlights. You need to iterate over highlight object in the response, which has the unique key as key and then extract the highlighted field that you are looking for. If this was confusing, put a breakpoint on the line immediately after you query (var results = ...) and then inspect results.Highlights. You will see what I am talking about.

**Comment by ksivanandan** [comment]
Thank you! Will try that out.

**Comment by ksivanandan** [comment]
Good Morning

I was able to keep a breakpoint and see the results. Highlights

My view Model

       [SolrField("health_content_t")]
        public string HealthContent { get; set; }

        [SolrField("description_t")]
        public string Description { get; set; }

        [SolrField("title_t")]
        public string Title { get; set; }

        [SolrField("_fullpath")]
        public string PageUrl { get; set; }


My Controller

var queryOption = new QueryOptions
                {
                    FilterQueries = BuildFilterQueries(parameters),
                    Rows = parameters.PageSize,
                    Start = start,
                    SpellCheck = new SpellCheckingParameters
                    {
                        Collate = true
                    },
                    Highlight = new HighlightingParameters
                    {
                        Fragsize = 250,
                        Fields = new[] { "*" },
                        BeforeTerm = "<b>",
                        AfterTerm = "</b>",
                        Snippets = 1
                    }

                };
var results = _searchResults.Query(BuildQuery(parameters), queryOption);

view = new SearchView
{
      EntireSiteResults = results,
      Search = parameters,
     TotalCount = results.NumFound,
     DidYouMean = GetSpellCheckingResult(results)
};


I am not sure how I iterate through the results. I would have to display

Title, fullpath, with bolded search term, also show the snippet of the healthContent with bolded search term

Looks like I have to iterate through the results.Highlights for each of these fields?

Any guidance please

Thanks

**Comment by xaviermorera** [comment]
Yes you have to iterate, please see that the key on Highlights matches the document id so use a foreach to go through them. Then on each one of the objects, the field name is also the key to get them from the list and extract the snippet with highlights. 

I believe that it is better for this kind of question to be posted to StackOverflow as iteration over an object is something that can be explained rather quickly by the many answerers of SO.

**Comment by ksivanandan** [comment]
I can use the foreach to iterate through the object, although I don't have Id as part of my SearchViewModel and hence foreach (var h in results.Highlights[results[0].Id]) throws an error
	
results.Highlights[results[0].Id]	error CS1061: 'SearchResultsViewModel' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'SearchResultsViewModel' could be found (are you missing a using directive or an assembly reference?)	

Thanks

**Comment by ksivanandan** [comment]
Although when I type in results.Highlights["9105"] I get the object back with Keys, Snippets and Values.

**Comment by xaviermorera** [comment]
Unique key should be in results if you add it to your model. And again, StackOverflow for support :)

**Comment by ksivanandan** [comment]
Yes thanks, I have posted the question there as well. Should I be using results.Highlights.Snippets?

**Comment by ksivanandan** [comment]
Also, will I be able to use the same viewmodel and swap the values for title, PageUrl, description and health_content with the ones from Highlight? Do you have any examples?

Thanks so much for all your help

**Comment by ksivanandan** [comment]
I was able to get this working!
Thank you
