### ISSUE TITLE
Compatibility with Solr 6

### ISSUE THREAD

**Issue by DumboJet** [mausch/SolrNet#244]
This is a question:

We were using Solr version 4 with this library and we are thinking of upgrading to Solr 6.
Does anyone know if  Solr 6 is supported by this library?
Are there any known issues for migrating to Solr 6?

Thanks! :)

**Comment by fatmuis** [comment]
Hi,

We recently migrated from Solr 4.5.0 to Solr 5.4.1 and had no problems with
SolrNet. Hope that helps.

2016-06-21 13:25 GMT+02:00 DumboJet <notifications@github.com>:

**Comment by DumboJet** [comment]
Thank you for the input @fatmuis. :)
This is a bit encouraging.
I just hope version 6 does not break anything. :)
Thanks. :)

**Comment by DumboJet** [comment]
I have just tried it and it works (from a first test).

**Comment by dddkiran** [comment]
@DumboJet,
Which version of solrNet r u using against solr6, I tried with SolrNet(0.4.0.2002) and it does not work.

Thank you :)

**Comment by DumboJet** [comment]
@dddkiran Hello. :)
I am using version 0.4.0.4001 of SolrNet.
One thing you should try, is to include the core or the collection name in the request URL: 
http://stackoverflow.com/a/2214672/2173353
And check that it works from the admin UI first.

**Comment by dddkiran** [comment]
@DumboJet  Thanks! :)
Will try that.
