### ISSUE TITLE
 Ninject.Integration.SolrNet (Version=0.5.0.1002) references Ninject 3.0.0

### ISSUE THREAD

**Issue by AddictedCS** [mausch/SolrNet#258]
Downloaded the dependencies via NuGet. In my project I have Ninject 3.2.x referenced. Got a runtime issue with missing Ninject 3.0.0.

`{"Could not load file or assembly 'Ninject, Version=3.0.0.0, Culture=neutral, PublicKeyToken=c7192dc5380945e7' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Ninject, Version=3.0.0.0, Culture=neutral, PublicKeyToken=c7192dc5380945e7"}`

Used ILSpy to understand where does this come from. It seems that  Ninject.Integration.SolrNet references Ninject.3.0.0 (which is not present in the NuGet repository BTW).
Extract from ILSpy
`// Ninject.Integration.SolrNet, Version=0.5.0.1002, Culture=neutral, PublicKeyToken=null` references
`// Ninject, Version=3.0.0.0, Culture=neutral, PublicKeyToken=c7192dc5380945e7`

Any help will be greatly appreciated!

**Comment by mausch** [comment]
Hi,

https://www.nuget.org/packages/SolrNet.Ninject/0.5.0-alpha2 declares `Ninject (>= 3.0.1.10)`.
That version of Ninject is available on nuget: https://www.nuget.org/packages/Ninject/3.0.1.10

**Comment by AddictedCS** [comment]
I've noticed the declaration. The issue is replicated when Ninject 3.2.x is already used by the project. In this case package manager does not download the v3.0.1.10, though runtime still fails with dependency problem.

**Comment by mausch** [comment]
Have you tried adding an assembly binding redirect?

**Comment by AddictedCS** [comment]
Yes, (I believe it got added by VS once I installed the package).
```<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Ninject" publicKeyToken="c7192dc5380945e7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>```

It may be caused by additional project reference: Main Project references Ninject and Solr.Ninject. Integration Test project references both Main Project and Solr.Ninject (I may have got it wrong here). Will try to debug.

**Comment by AddictedCS** [comment]
Fixed, it was a local issue.
