### ISSUE TITLE
Indexing problem in solr net

### ISSUE THREAD

**Issue by waleedraza786** [mausch/SolrNet#265]
An unhandled exception of type 'SolrNet.Exceptions.SolrConnectionException' occurred in SolrNet.dll

Additional information: <?xml version="1.0" encoding="UTF-8"?>

<response>

<lst name="responseHeader"><int name="status">400</int><int name="QTime">400</int></lst><lst name="error"><lst name="metadata"><str name="error-class">org.apache.solr.common.SolrException</str><str name="root-error-class">org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException</str></lst><str name="msg">Exception writing document id ff81010c-3510-48e0-9618-7398c8e75deb to the index; possible analysis error: Document contains at least one immense term in field="doctext" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[50, 52, 48, 48, 32, 65, 46, 68, 46, 32, 67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 49, 57, 56, 55, 32, 79, 114, 105, 103, 105]...', original message: bytes can be at most 32766 in length; got 41389. Perhaps the document has an indexed string field (solr.StrField) which is too large</str><int name="code">400</int></lst>

</response>

**Comment by xavier-morera** [comment]
This does not seem to be a SolrNet error. It is an analysis error which has occurred to a few other people. Check this out: http://stackoverflow.com/questions/29445323/adding-a-document-to-the-index-in-solr-document-contains-at-least-one-immense-t

Perhaps doctext should not be StrField and instead it should be text. Depends on what you are using it for.

**Comment by waleedraza786** [comment]
Thanks :)
